In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])
c = a*b
print(c)

[ 10  40  90 160]


In [3]:
a = np.array([[1,2,3,4],[6,3,1,8],[8,1,2,4]])

b = np.array([10,20,30,40])

c = a*b

print(c)

[[ 10  40  90 160]
 [ 60  60  30 320]
 [ 80  20  60 160]]


In [11]:
for item in np.nditer(c):
    print(item)

10
40
90
160
60
60
30
320
80
20
60
160


In [6]:
for item in a:
    for element in item:
        print(element)

1
2
3
4
6
3
1
8
8
1
2
4


In [7]:
num1 = np.arange(0,60,5)
num1 = num1.reshape(3,4)
print(num1)

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


In [10]:
num2 = num1.T
num2

array([[ 0, 20, 40],
       [ 5, 25, 45],
       [10, 30, 50],
       [15, 35, 55]])

In [13]:
for item in np.nditer(num2):
    print(item)

0
5
10
15
20
25
30
35
40
45
50
55


In [15]:
for item in np.nditer(num2,order='C'):
    print(item)

0
20
40
5
25
45
10
30
50
15
35
55


In [16]:
for item in np.nditer(num2,order='F'):
    print(item)

0
5
10
15
20
25
30
35
40
45
50
55


In [17]:
print(num1)

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


In [19]:
num1*2

array([[  0,  10,  20,  30],
       [ 40,  50,  60,  70],
       [ 80,  90, 100, 110]])

In [22]:
for item in np.nditer(num1, op_flags=['readwrite']):
    item[...] = 2*item
    
num1

array([[  0,  20,  40,  60],
       [ 80, 100, 120, 140],
       [160, 180, 200, 220]])

In [24]:
a = np.arange(8)
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [25]:
b = a.reshape(4,2)
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [26]:
b.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [31]:
a = np.array([[1,2],[3,4]])
b= np.array([[5,6],[7,8]])

c = np.concatenate((a,b), axis=1)
c

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [38]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print('=====================')
b = np.resize(a,(3,3))
print(b)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [1 2 3]]


In [40]:
a = np.char.add(['Hello '],['Winner'])
print(a)

['Hello Winner']


In [41]:
b = np.char.upper('hello')
b

array('HELLO', dtype='<U5')

In [42]:
a = np.array([0,30,45,60,90])
print(a)

[ 0 30 45 60 90]


In [43]:
print(np.sin(a*np.pi/180))

[0.         0.5        0.70710678 0.8660254  1.        ]


In [44]:
print(np.cos(a*np.pi/180))

[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


In [45]:
print(np.tan(a*np.pi/180))

[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [46]:
sin = np.sin(a*np.pi/180)

In [47]:
inv = np.arcsin(sin)
inv

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [48]:
print(np.degrees(inv))

[ 0. 30. 45. 60. 90.]


In [49]:
a = np.arange(9,dtype=np.float_).reshape(3,3)
print(a)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


In [50]:
b = np.array([10,10,10])
b

array([10, 10, 10])

In [51]:
a+b

array([[10., 11., 12.],
       [13., 14., 15.],
       [16., 17., 18.]])

In [52]:
np.add(a,b)

array([[10., 11., 12.],
       [13., 14., 15.],
       [16., 17., 18.]])

In [53]:
a-b

array([[-10.,  -9.,  -8.],
       [ -7.,  -6.,  -5.],
       [ -4.,  -3.,  -2.]])

In [54]:
np.subtract(a,b)

array([[-10.,  -9.,  -8.],
       [ -7.,  -6.,  -5.],
       [ -4.,  -3.,  -2.]])

In [55]:
np.power(a,2)

array([[ 0.,  1.,  4.],
       [ 9., 16., 25.],
       [36., 49., 64.]])

In [56]:
a

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [57]:
np.std([1,2,3,4])

1.118033988749895

In [59]:
a = np.array([1,2,3,4])
std = np.std(a)
print(std)

1.118033988749895


In [60]:
np.var([1,2,3,4])

1.25

In [61]:
a = np.array([1,2,3,4])
var = np.var(a)
print(var)

1.25
